### PR TITLE
Adapter for Zend_Db (ZF1)

### PR DESCRIPTION
**Pull request by tomasfejfar**

### CODE REVIEW

**Comment by bartko-s** [comment]
Hi @tomasfejfar, great job. But your implementation has one little issue. Original ZF1 db adapter which is used in your implementation does not support nested transaction like [Doctrine DBAL](http://doctrine-orm.readthedocs.org/projects/doctrine-dbal/en/latest/reference/transactions.html#transaction-nesting) or [Stefano DB](https://github.com/bartko-s/stefano-db) which are used in other adapters and support this behaviours.

**Comment by tomasfejfar** [comment]
Are nested transactions actually used somewhere in the actual code? I don't believe so (tests worked for me). 

There a few options I see:
* add switch to disable the "inner" transactions (to allow outside transaction)
    * I could listen to exception on transaction start, check for duplicate transaction and offer to turn inner transactions off in the exception message
* create adapter that will wrap the inner adapter and offer transactions

I think first option would be good enough. It will also make the developer willfully accept the fact that the transactions needs to be handled on the application level. 

What do you think?

**Comment by bartko-s** [comment]
No, nested transaction are not used in the actual code. Tests worked because this behaviour is not tested. I will add this test.

Switch which disable inner transaction is not acceptable for me.  It is not clean and robust enough.
From my point of view an adapter is better solution.

Do you have any other questions?

**Comment by tomasfejfar** [comment]
I tried using it on the actual project and having the adapter inside the project is clumsy - the whole project would need dependencies to your Transaction and LockTable... extracting to separate package seems as a sensible solution. I'll try to do it asap

**Comment by bartko-s** [comment]
I am also working on a ZF1 adapter. It is almost done.

**Comment by bartko-s** [comment]
Support for ZF1 was added and new version 1.4.0 was released.

**Comment by tomasfejfar** [comment]
Great! Thanks a lot. I'll try it tomorrow with my existing code...

**Pull request merged**
